-- شغّل هذا الملف مرة واحدة داخل Supabase SQL Editor

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  name text not null,
  cat text,
  wood text,
  finish text,
  duration text,
  image text,
  description text,
  details text,
  gallery jsonb default '[]'::jsonb,
  videos jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  created_at timestamptz default now()
);

create table if not exists public.materials (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  created_at timestamptz default now()
);

alter table public.projects enable row level security;
alter table public.services enable row level security;
alter table public.materials enable row level security;

drop policy if exists "public read projects" on public.projects;
drop policy if exists "public insert projects" on public.projects;
drop policy if exists "public update projects" on public.projects;
drop policy if exists "public delete projects" on public.projects;
create policy "public read projects" on public.projects for select using (true);
create policy "public insert projects" on public.projects for insert with check (true);
create policy "public update projects" on public.projects for update using (true);
create policy "public delete projects" on public.projects for delete using (true);

drop policy if exists "public read services" on public.services;
drop policy if exists "public insert services" on public.services;
drop policy if exists "public update services" on public.services;
drop policy if exists "public delete services" on public.services;
create policy "public read services" on public.services for select using (true);
create policy "public insert services" on public.services for insert with check (true);
create policy "public update services" on public.services for update using (true);
create policy "public delete services" on public.services for delete using (true);

drop policy if exists "public read materials" on public.materials;
drop policy if exists "public insert materials" on public.materials;
drop policy if exists "public update materials" on public.materials;
drop policy if exists "public delete materials" on public.materials;
create policy "public read materials" on public.materials for select using (true);
create policy "public insert materials" on public.materials for insert with check (true);
create policy "public update materials" on public.materials for update using (true);
create policy "public delete materials" on public.materials for delete using (true);

insert into public.projects (name, cat, wood, finish, duration, image, description, details, gallery, videos)
values
('مطبخ Walnut House','مطابخ','Walnut Veneer','Matte PU','28 يوم','assets/projects/project-1.png','مطبخ دافئ بخطوط نظيفة، تخزين مخفي، وإضاءة مدمجة.','مطبخ دافئ بخطوط نظيفة، تخزين مخفي، وإضاءة مدمجة.','["assets/projects/project-1.png"]','[]'),
('غرفة ملابس Alia Suite','خزائن','Oak Veneer','Natural Oil','18 يوم','assets/projects/project-2.png','غرفة ملابس مفتوحة بتقسيمات دقيقة وإحساس فندقي هادئ.','غرفة ملابس مفتوحة بتقسيمات دقيقة وإحساس فندقي هادئ.','["assets/projects/project-2.png"]','[]'),
('واجهة متجر Atelier','تجاري','Ash Wood','Warm Stain','21 يوم','assets/projects/project-3.png','واجهة وتجهيز داخلي يعكسان جودة البراند من أول نظرة.','واجهة وتجهيز داخلي يعكسان جودة البراند من أول نظرة.','["assets/projects/project-3.png"]','[]'),
('مكتب Executive','أثاث','Solid Beech','Satin Lacquer','12 يوم','assets/projects/project-4.png','مكتب تفصيل بسطح واسع وتفاصيل نحاسية خفيفة.','مكتب تفصيل بسطح واسع وتفاصيل نحاسية خفيفة.','["assets/projects/project-4.png"]','[]')
on conflict do nothing;

insert into public.services (title, description)
values
('مطابخ حسب الطلب','تصميم عملي هادئ، توزيع ذكي، وخامات تتحمل الاستخدام اليومي بأناقة.'),
('خزائن وغرف ملابس','حلول تخزين مصممة على القياس بتفاصيل داخلية مدروسة وتشطيبات راقية.'),
('أبواب خشبية','أبواب داخلية وخارجية بتناسق بين الصلابة، الصوت، والملمس.'),
('أثاث تفصيل','قطع مفصلة للمساحة، تعكس شخصية المكان بدون مبالغة.'),
('ديكورات خشبية','جدران، فواصل، أسقف، وملامح دافئة تضيف عمقًا بصريًا للمكان.'),
('مكاتب ومحلات تجارية','تنفيذ واجهات ومساحات عمل تحمل هوية المكان وتخدم الحركة اليومية.')
on conflict do nothing;

insert into public.materials (title, description)
values
('خشب Walnut','لون عميق وحضور فاخر للمطابخ والأثاث الراقي.'),
('قشرة Oak','ملمس طبيعي ونبرة هادئة للمساحات الحديثة.'),
('مفصلات Soft Close','إغلاق ناعم وصامت لعمر استخدام أطول.'),
('مقابض مخفية','خطوط نظيفة وتجربة استخدام مريحة.'),
('تشطيب Matte PU','حماية عالية ولمسة غير لامعة أنيقة.'),
('ألوان مخصصة','درجات مدروسة حسب الإضاءة والفراغ.')
on conflict do nothing;
