-- شغّل هذا الملف داخل Supabase SQL Editor.
-- قبل التشغيل: أنشئ مستخدم الأدمن من Authentication > Users > Add user.

create table if not exists public.site_settings (
  id int primary key default 1,
  key text not null default 'main' unique,
  content jsonb not null default '{}'::jsonb,
  updated_at timestamptz default now()
);

alter table public.site_settings add column if not exists key text not null default 'main';
create unique index if not exists site_settings_key_unique on public.site_settings(key);

-- كل مستخدم موجود وقت تشغيل الملف يُعتمد كأدمن. المستخدمون الجدد لا يحصلون على الصلاحية تلقائياً.
create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  created_at timestamptz default now()
);
alter table public.admin_users enable row level security;
insert into public.admin_users (user_id, email)
select id, email from auth.users where email is not null
on conflict (user_id) do update set email = excluded.email;

create or replace function public.is_site_admin()
returns boolean language sql stable security definer set search_path = public
as $$ select exists(select 1 from public.admin_users where user_id = auth.uid()) $$;
revoke all on function public.is_site_admin() from public;
grant execute on function public.is_site_admin() to anon, authenticated;

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  name text not null,
  cat text,
  wood text,
  finish text,
  duration text,
  image text,
  description text,
  details text,
  gallery jsonb default '[]'::jsonb,
  videos jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  created_at timestamptz default now()
);

create table if not exists public.materials (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  created_at timestamptz default now()
);

alter table public.site_settings enable row level security;
alter table public.projects enable row level security;
alter table public.services enable row level security;
alter table public.materials enable row level security;

drop policy if exists "public read site_settings" on public.site_settings;
drop policy if exists "admin write site_settings" on public.site_settings;
create policy "public read site_settings" on public.site_settings for select using (true);
create policy "admin write site_settings" on public.site_settings for all using (public.is_site_admin()) with check (public.is_site_admin());

drop policy if exists "public read projects" on public.projects;
drop policy if exists "admin write projects" on public.projects;
create policy "public read projects" on public.projects for select using (true);
create policy "admin write projects" on public.projects for all using (public.is_site_admin()) with check (public.is_site_admin());

drop policy if exists "public read services" on public.services;
drop policy if exists "admin write services" on public.services;
create policy "public read services" on public.services for select using (true);
create policy "admin write services" on public.services for all using (public.is_site_admin()) with check (public.is_site_admin());

drop policy if exists "public read materials" on public.materials;
drop policy if exists "admin write materials" on public.materials;
create policy "public read materials" on public.materials for select using (true);
create policy "admin write materials" on public.materials for all using (public.is_site_admin()) with check (public.is_site_admin());

-- Storage bucket للصور والفيديوهات التي ترفعها من لوحة الأدمن
insert into storage.buckets (id, name, public)
values ('site-assets', 'site-assets', true)
on conflict (id) do update set public = true;

drop policy if exists "public read site-assets" on storage.objects;
drop policy if exists "admin upload site-assets" on storage.objects;
drop policy if exists "admin update site-assets" on storage.objects;
drop policy if exists "admin delete site-assets" on storage.objects;
create policy "public read site-assets" on storage.objects for select using (bucket_id = 'site-assets');
create policy "admin upload site-assets" on storage.objects for insert with check (bucket_id = 'site-assets' and public.is_site_admin());
create policy "admin update site-assets" on storage.objects for update using (bucket_id = 'site-assets' and public.is_site_admin()) with check (bucket_id = 'site-assets' and public.is_site_admin());
create policy "admin delete site-assets" on storage.objects for delete using (bucket_id = 'site-assets' and public.is_site_admin());

-- المحتوى الافتراضي يضاف فقط إذا كانت الجداول فارغة، ولا يحذف تعديلاتك عند إعادة تشغيل الملف.

insert into public.site_settings (id, key, content, updated_at)
values (1, 'main', '{
  "logo":"assets/logo.png",
  "heroVideo":"assets/media/hero-wood.mp4",
  "heroPoster":"assets/projects/project-1.png",
  "heroEyebrow":"Luxury Woodworks / Interior Craftsmanship",
  "heroTitle":"النجارة مش بس شغل إيدين<br><span>تصميم بعقل قبل التنفيذ</span><br>تنفيذ لآخر مسمار",
  "heroLead":"نجارة داخلية تُبنى على القياس، الخامة، والإحساس الهادئ بالفخامة.",
  "aboutTitle":"ورشة راقية تبدأ بالفكرة قبل المنشار.",
  "aboutLead":"نصمم الخشب كجزء من هوية المكان، لا كقطعة منفصلة عنه.",
  "aboutText1":"Bassam Sabatin Woodworks براند نجارة وتصميم داخلي يوازن بين الذوق، الدقة، والخبرة العملية. قبل التنفيذ نقرأ المساحة، الإضاءة، الحركة اليومية، وشخصية العميل.",
  "aboutText2":"الفخامة عندنا ليست زحمة تفاصيل؛ هي قياس صحيح، خامة محترمة، حواف نظيفة، وتركيب لا يترك صدفة.",
  "servicesTitle":"تفصيل فاخر للمساحات التي تستحق.",
  "portfolioTitle":"مشاريع مصممة لتبدو هادئة وغالية.",
  "contactTitle":"احكِ لنا عن المساحة، ونحوّلها لخطة تنفيذ واضحة.",
  "contactLead":"أرسل صورًا أو مراجع أو وصفًا بسيطًا، وسنرتب التفاصيل خطوة بخطوة.",
  "whatsapp":"962798234541"
}'::jsonb, now())
on conflict (id) do nothing;

insert into public.projects (name, cat, wood, finish, duration, image, description, details, gallery, videos)
select * from (values
('مطبخ Walnut House','مطابخ','Walnut Veneer','Matte PU','28 يوم','assets/projects/project-1.png','مطبخ دافئ بخطوط نظيفة، تخزين مخفي، وإضاءة مدمجة.','مطبخ دافئ بخطوط نظيفة، تخزين مخفي، وإضاءة مدمجة.','["assets/projects/project-1.png"]','[]'),
('غرفة ملابس Alia Suite','خزائن','Oak Veneer','Natural Oil','18 يوم','assets/projects/project-2.png','غرفة ملابس مفتوحة بتقسيمات دقيقة وإحساس فندقي هادئ.','غرفة ملابس مفتوحة بتقسيمات دقيقة وإحساس فندقي هادئ.','["assets/projects/project-2.png"]','[]'),
('واجهة متجر Atelier','تجاري','Ash Wood','Warm Stain','21 يوم','assets/projects/project-3.png','واجهة وتجهيز داخلي يعكسان جودة البراند من أول نظرة.','واجهة وتجهيز داخلي يعكسان جودة البراند من أول نظرة.','["assets/projects/project-3.png"]','[]'),
('مكتب Executive','أثاث','Solid Beech','Satin Lacquer','12 يوم','assets/projects/project-4.png','مكتب تفصيل بسطح واسع وتفاصيل نحاسية خفيفة.','مكتب تفصيل بسطح واسع وتفاصيل نحاسية خفيفة.','["assets/projects/project-4.png"]'::jsonb,'[]'::jsonb)) as seed(name,cat,wood,finish,duration,image,description,details,gallery,videos)
where not exists (select 1 from public.projects);

insert into public.services (title, description)
select * from (values
('مطابخ حسب الطلب','تصميم عملي هادئ، توزيع ذكي، وخامات تتحمل الاستخدام اليومي بأناقة.'),
('خزائن وغرف ملابس','حلول تخزين مصممة على القياس بتفاصيل داخلية مدروسة وتشطيبات راقية.'),
('أبواب خشبية','أبواب داخلية وخارجية بتناسق بين الصلابة، الصوت، والملمس.'),
('أثاث تفصيل','قطع مفصلة للمساحة، تعكس شخصية المكان بدون مبالغة.'),
('ديكورات خشبية','جدران، فواصل، أسقف، وملامح دافئة تضيف عمقًا بصريًا للمكان.'),
('مكاتب ومحلات تجارية','تنفيذ واجهات ومساحات عمل تحمل هوية المكان وتخدم الحركة اليومية.')) as seed(title,description)
where not exists (select 1 from public.services);

insert into public.materials (title, description)
select * from (values
('خشب Walnut','لون عميق وحضور فاخر للمطابخ والأثاث الراقي.'),
('قشرة Oak','ملمس طبيعي ونبرة هادئة للمساحات الحديثة.'),
('مفصلات Soft Close','إغلاق ناعم وصامت لعمر استخدام أطول.'),
('مقابض مخفية','خطوط نظيفة وتجربة استخدام مريحة.'),
('تشطيب Matte PU','حماية عالية ولمسة غير لامعة أنيقة.'),
('ألوان مخصصة','درجات مدروسة حسب الإضاءة والفراغ.')) as seed(title,description)
where not exists (select 1 from public.materials);
